CREATE TABLE monitoring_attempts (
    attempt_id VARCHAR(128) PRIMARY KEY,
    candidate_user_id BIGINT NOT NULL REFERENCES user_accounts(id),
    state VARCHAR(16) NOT NULL CHECK (state IN ('ACTIVE', 'CLOSED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE monitoring_proctor_assignments (
    attempt_id VARCHAR(128) NOT NULL REFERENCES monitoring_attempts(attempt_id),
    proctor_user_id BIGINT NOT NULL REFERENCES user_accounts(id),
    PRIMARY KEY (attempt_id, proctor_user_id)
);
CREATE TABLE monitoring_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id VARCHAR(128) NOT NULL REFERENCES monitoring_attempts(attempt_id),
    event_id VARCHAR(128) NOT NULL,
    collector_session_id VARCHAR(128) NOT NULL,
    policy_version VARCHAR(128) NOT NULL,
    pid BIGINT NOT NULL CHECK (pid > 0),
    process_name VARCHAR(255) NOT NULL,
    process_start_instant TIMESTAMPTZ,
    metadata_quality VARCHAR(16) NOT NULL CHECK (metadata_quality IN ('COMPLETE', 'UNREADABLE')),
    observed_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT monitoring_event_identity UNIQUE (attempt_id, event_id)
);
CREATE INDEX monitoring_timeline_order ON monitoring_events(attempt_id, received_at, id);
CREATE INDEX monitoring_candidate_scope ON monitoring_attempts(candidate_user_id, state);
CREATE INDEX monitoring_proctor_scope ON monitoring_proctor_assignments(proctor_user_id, attempt_id);
