-- C3 overflow reports are history only; never update process/presence state.
CREATE TABLE monitoring_gaps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id VARCHAR(128) NOT NULL REFERENCES monitoring_attempts(attempt_id),
    gap_id VARCHAR(128) NOT NULL,
    collector_session_id VARCHAR(128) NOT NULL,
    reason VARCHAR(32) NOT NULL CHECK (reason = 'QUEUE_OVERFLOW'),
    dropped_count BIGINT NOT NULL CHECK (dropped_count > 0),
    first_dropped_at TIMESTAMPTZ NOT NULL,
    last_dropped_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT monitoring_gap_interval CHECK (last_dropped_at >= first_dropped_at),
    CONSTRAINT monitoring_gap_identity UNIQUE (attempt_id,gap_id)
);
CREATE INDEX monitoring_gap_timeline ON monitoring_gaps(attempt_id,received_at,id);
