-- V5: Exams, Questions, Options, Exam Sessions and Attempt metadata

CREATE TABLE exams (
    exam_id VARCHAR(128) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    total_questions INT NOT NULL CHECK (total_questions > 0),
    created_by BIGINT NOT NULL REFERENCES user_accounts(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE exam_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id VARCHAR(128) NOT NULL REFERENCES exams(exam_id) ON DELETE CASCADE,
    question_id VARCHAR(128) NOT NULL,
    section VARCHAR(32) NOT NULL CHECK (section IN ('LISTENING', 'READING')),
    part INT NOT NULL CHECK (part BETWEEN 1 AND 7),
    group_id VARCHAR(128),
    passage_text TEXT,
    audio_file VARCHAR(255),
    prompt TEXT NOT NULL,
    correct_option VARCHAR(32) NOT NULL,
    order_index INT NOT NULL,
    CONSTRAINT exam_question_identity UNIQUE (exam_id, question_id)
);

CREATE TABLE exam_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id VARCHAR(128) NOT NULL,
    question_id VARCHAR(128) NOT NULL,
    option_id VARCHAR(32) NOT NULL,
    option_text TEXT NOT NULL,
    order_index INT NOT NULL,
    FOREIGN KEY (exam_id, question_id) REFERENCES exam_questions(exam_id, question_id) ON DELETE CASCADE,
    CONSTRAINT exam_option_identity UNIQUE (exam_id, question_id, option_id)
);

CREATE TABLE exam_sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    exam_id VARCHAR(128) NOT NULL REFERENCES exams(exam_id),
    title VARCHAR(255) NOT NULL,
    duration_seconds INT NOT NULL CHECK (duration_seconds > 0),
    state VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED' CHECK (state IN ('SCHEDULED', 'IN_PROGRESS', 'CLOSED')),
    created_by BIGINT NOT NULL REFERENCES user_accounts(id),
    started_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE exam_session_proctors (
    session_id VARCHAR(128) NOT NULL REFERENCES exam_sessions(session_id) ON DELETE CASCADE,
    proctor_user_id BIGINT NOT NULL REFERENCES user_accounts(id),
    PRIMARY KEY (session_id, proctor_user_id)
);

-- Extend monitoring_attempts for Exam Lifecycle & Answers Concurrency
ALTER TABLE monitoring_attempts ADD COLUMN session_id VARCHAR(128) REFERENCES exam_sessions(session_id);
ALTER TABLE monitoring_attempts ADD COLUMN exam_id VARCHAR(128) REFERENCES exams(exam_id);
ALTER TABLE monitoring_attempts ADD COLUMN deadline_at TIMESTAMPTZ;
ALTER TABLE monitoring_attempts ADD COLUMN writer_epoch BIGINT NOT NULL DEFAULT 1;
ALTER TABLE monitoring_attempts ADD COLUMN saved_revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE monitoring_attempts ADD COLUMN submitted_at TIMESTAMPTZ;
ALTER TABLE monitoring_attempts ADD COLUMN score INT;
ALTER TABLE monitoring_attempts ADD COLUMN answers_json TEXT NOT NULL DEFAULT '{}';

ALTER TABLE monitoring_attempts DROP CONSTRAINT monitoring_attempts_state_check;
ALTER TABLE monitoring_attempts ADD CONSTRAINT monitoring_attempts_state_check 
    CHECK (state IN ('ACTIVE', 'CLOSED', 'SUBMITTED', 'TIMED_OUT', 'INTERRUPTED'));

CREATE INDEX idx_exam_questions_exam_order ON exam_questions(exam_id, order_index);
CREATE INDEX idx_exam_options_question ON exam_options(exam_id, question_id, order_index);
CREATE INDEX idx_exam_sessions_exam ON exam_sessions(exam_id);
CREATE INDEX idx_monitoring_attempts_session ON monitoring_attempts(session_id);
